# Generated by Django 4.2.8 on 2024-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_address_location_alter_address_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='uid',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('both', 'Both')], default='both', max_length=50),
        ),
    ]
